version: '2'

services:

  restyaboard:
    build: .
    ports:
      - 1234:80
    volumes:
       - /var/opt/restya/media:/usr/share/nginx/html/media
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
      - SMTP_DOMAIN=domain
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=pass
      - SMTP_SERVER=server
      - SMTP_PORT=465
    depends_on:
      - postgres
    restart: always

  postgres:
    image: kiasaki/alpine-postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
    restart: always
